Team-useMemo/Jugger-Backend

.github/workflows/deploy.yml, src/main/java/com/usememo/jugger/domain/health/controller/HealthController.java
#16 https 설정입니다.
https 설정을 위한 마지막 단계에서 아래 사진과 같이 로드밸런서의 상태를 지속적으로 확인하는 API 가 필요하기에 API 만들었습니다.
따로 테스트 코드를 작성하는 것은 의미가 없을 것 같아. 위의 이미지와 같이 로컬에서 테스트했습니다.
위의 이미지와 같이 동작확인 했습니다
=> feat : health 체크를 하기 위한 API 추가입니다.  #16

.github/workflows/deploy.yml, Dockerfile, build.gradle, src/main/java/com/usememo/jugger/domain/calendar/entity/Calendar.java, src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java, src/main/java/com/usememo/jugger/domain/category/dto/PostCategoryDto.java, src/main/java/com/usememo/jugger/domain/category/entity/Category.java, src/main/java/com/usememo/jugger/domain/category/repository/CategoryRepository.java, src/main/java/com/usememo/jugger/domain/category/service/CategoryService.java, src/main/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementation.java, src/main/java/com/usememo/jugger/domain/chat/entity/Chat.java, src/main/java/com/usememo/jugger/domain/health/controller/HealthController.java, src/main/java/com/usememo/jugger/domain/link/entity/Link.java, src/main/java/com/usememo/jugger/domain/photo/entity/Photo.java, src/main/java/com/usememo/jugger/domain/user/entity/User.java, src/main/java/com/usememo/jugger/domain/versionHistory/entity/VersionHistory.java, src/main/resources/application.yml, src/test/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementationTest.java
메인에 지금까지 진행했던 것들 merge해서 ci/cd 확인하겠습니다.
=> feat : 현재까지 dev에 개발된 것에 대해서 main에 merge

.gitignore, build.gradle, src/main/java/com/usememo/jugger/global/exception/ErrorCode.java, src/main/java/com/usememo/jugger/global/exception/s3/S3UploadException.java, src/main/java/com/usememo/jugger/global/s3/controller/S3Controller.java, src/main/java/com/usememo/jugger/global/s3/service/S3Service.java, src/main/java/com/usememo/jugger/global/s3/service/S3ServiceImplementation.java, src/main/resources/application.yml, src/test/java/com/usememo/jugger/global/s3/service/S3ServiceImplementationTest.java, src/test/java/com/usememo/jugger/global/s3/service/S3ServiceTest.java
- #20 
S3를 통해서 이미지를 등록하기 위해서 S3 버킷에 대한 설정을 마쳤습니다.
UUID로 업로드한 url를 구성하였습니다.
또한 파일의 위치를 global로 두어서 어떤 domain에서든 사용할 수 있게 해두었습니다.
이건 추후에 조정해도 좋을 것 같습니다.
또한 application.yml 파일은 삭제해두었습니다. gihub secret에 설정들을 넣어두어서 배포 시에 문제 없게 설정해둘 예정입니다.
=> feat : S3 버킷 등록

.github/workflows/deploy.yml
=> hotfix : 테스트

.github/workflows/deploy.yml
delploy.yml 수정
deploy.yml에 secret 키 값이랑 달라서 오류가 발생한 듯합니다.
MONGO_URI로 되어있어서 MONGO_URL로 수정하였습니다
=> hotfix : deploy 설정변경

.github/workflows/deploy.yml
=> hotfix : 테스트 (#29)

.github/workflows/deploy.yml
=> hotfix : main과 dev에 대한 버전 일치시키기 위함

.github/workflows/deploy.yml
=> hotfix : main 과 dev 브렌치 정상화

src/main/java/com/usememo/jugger/domain/category/repository/CategoryRepository.java, src/main/java/com/usememo/jugger/domain/link/controller/LinkController.java, src/main/java/com/usememo/jugger/domain/link/dto/GetLinkDto.java, src/main/java/com/usememo/jugger/domain/link/entity/Link.java, src/main/java/com/usememo/jugger/domain/link/repository/LinkRepository.java, src/main/java/com/usememo/jugger/domain/link/service/LinkService.java, src/main/java/com/usememo/jugger/domain/link/service/LinkServiceImplementation.java, src/main/resources/application.yml, src/test/java/com/usememo/jugger/domain/link/service/LinkServiceImplementationTest.java
=> feat: 링크조회 API 개발

.gitignore, src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java, src/main/java/com/usememo/jugger/domain/chat/controller/ChatController.java, src/main/java/com/usememo/jugger/domain/chat/repository/ChatRepository.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatService.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java, src/main/resources/application.yml, src/test/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementationTest.java
- #8
- 카테고리별 채팅조회를 구현했습니다!
[before]
[after]
=> feat: 카테고리별 채팅 조회

.github/workflows/deploy.yml, src/main/resources/application.yml
#40
기존에 main에 merge 시에만 배포되었을 때 억지로 main에 merge하다 보니 깃이 꼬이는 문제가 발생했었습니다! 
해당 문제를 해결하기 위해서 main이랑 dev에 push하면 배포될 수 있게끔 수정하였습니다.
위의 사진과 같이 수정하였습니다!
=> fix : deploy.yml push에 동작하게 수정 #40

src/main/java/com/usememo/jugger/domain/photo/controller/PhotoController.java, src/main/java/com/usememo/jugger/domain/photo/dto/GetPhotoDto.java, src/main/java/com/usememo/jugger/domain/photo/dto/GetPhotoRequestDto.java, src/main/java/com/usememo/jugger/domain/photo/entity/Photo.java, src/main/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementation.java, src/test/java/com/usememo/jugger/domain/calendar/service/CalendarServiceImplementationTest.java, src/test/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementationTest.java
- #46 
기존에는 user_uuid도 입력을 받아서 url만 제공해줬었는데 해당 부분에 대해서 수정하여
위의 사진과 같이 list형식으로 시간과, category_uuid로 찾은 category의 이름을 함께 전달해주게 수정하였습니다!
쩡킹님이 확인해주셨으면 하는게 쩡킹님 Calendar관련 테스트 코드에 생성자 관련해서 오류가 있어서 
위의 사진과 같이 categoryRepository 추가하여 오류해결하고 테스트 제대로 동작하는 것 확인하였습니다.
=> refactor : photo get 관련해서 수정

src/main/java/com/usememo/jugger/global/config/CorsConfig.java
- #49 
프론트엔드에서 프록시를 사용하지 않고 API 요청을 할 수 있도록 CORS 설정을 진행했습니다!
이 3개의 경로를 열어두었습니다.
추가로 CORS 설정부터하고 추가로 Security 달아서 JWT 관련 설정 진행하겠습니다.
=> feat : CORS 설정 추가

build.gradle, src/main/java/com/usememo/jugger/domain/calendar/controller/CalendarController.java, src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java, src/main/java/com/usememo/jugger/domain/chat/controller/ChatController.java, src/main/java/com/usememo/jugger/domain/health/controller/HealthController.java, src/main/java/com/usememo/jugger/domain/link/controller/LinkController.java, src/main/java/com/usememo/jugger/domain/photo/controller/PhotoController.java, src/main/java/com/usememo/jugger/global/config/SwaggerConfig.java
- #54 
- swagger가 없으니 너무 답답해서 만들었습니다!
- http://localhost:8080/webjars/swagger-ui/index.html#/ 로 접속하시면 되어요!
=> feat: swagger 추가

src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java, src/main/java/com/usememo/jugger/domain/category/dto/GetRecentCategoryDto.java, src/main/java/com/usememo/jugger/domain/category/entity/Category.java, src/main/java/com/usememo/jugger/domain/category/repository/CategoryRepository.java, src/main/java/com/usememo/jugger/domain/category/service/CategoryService.java, src/main/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementation.java, src/main/java/com/usememo/jugger/domain/chat/repository/ChatRepository.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatService.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java, src/test/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementationTest.java
- #53 
- #53이슈에서 프론트 개발자분들이 요청해주신 사항 맞춰서 해당 PR에서 수정하였습니다.
- 아래 캡처화면처럼 데이터들이 리턴됩니다.
- 스웨거 PR 머지 후에 이거 머지할게요! 얘도 스웨거 필요할것 같네염
=> refactor: 카테고리 조회 로직 수정

src/main/java/com/usememo/jugger/JuggerApplication.java, src/main/java/com/usememo/jugger/domain/calendar/entity/Calendar.java, src/main/java/com/usememo/jugger/domain/chat/dto/GetChatByCategoryDto.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java, src/main/java/com/usememo/jugger/domain/link/entity/Link.java, src/main/java/com/usememo/jugger/domain/photo/entity/Photo.java
- #59 
- 채팅(메모) 로직을 프론트 분들이 말씀하신대로 일괄 수정했습니다.
- 추가적으로 배포 서버에서 swagger cors걸려서 이것도 수정했어요 (다시 확인해보긴 해야할듯여)
- 데이터 다 안채우면 Null로 처리했습니당
=> refactor: swagger cors, 채팅 로직 수정

.github/workflows/deploy.yml
- #63 
deploy.yml에 secret에 넣어둔 키값들을 추가함으로써 배포될 때 발생한 문제를 해결하였습니다.
우선 작성했는데, 아마 오타가 발생하지 않는 이상 제대로 동작하게 될 것 같습니다!
=> fix : deploy.yml에 필요한 키들 추가 #63

src/main/java/com/usememo/jugger/global/config/SecurityConfig.java
- #69 
- Stateless하게 설정하기 위해서 코드 한줄 추가했습니다!
=> refactor: filter에 non session 방식 설정

.github/workflows/deploy.yml
- #63 
오타,,s가 빠진 오타 발견해서 수정했습니다.
이제 정상동작 될 것 같습니다
=> fix : deploy 오타수정 #63

src/main/java/com/usememo/jugger/global/config/CorsConfig.java, src/main/java/com/usememo/jugger/global/config/SwaggerConfig.java
=> feat: swagger auth token 설정 추가

src/main/java/com/usememo/jugger/domain/user/repository/UserRepository.java, src/main/java/com/usememo/jugger/global/exception/ErrorCode.java, src/main/java/com/usememo/jugger/global/security/token/service/KakaoOAuthService.java
=> fix : 중복유저에 대한 처리 진행 

src/main/java/com/usememo/jugger/global/config/SecurityConfig.java
- #82 
이거는 조금 꼼꼼하게 봐주셨으면 감사하겠습니다!!
일단은 
이 친구를 추가하긴 했는데, 아마 안쓸 것 같긴합니다. 찾아보니까 방식이 이렇게 설정을 security에 넣어줘서 security 단계에서 cors를 필터링하는 방식이랑 쩡킹이 진행했던 corsfilter를 따로 구성하는 방식이 있더라구요.
저 코드는 일단 첫번째 방식에 대한 코드인데 혹시 지금 바꾼 것에 대해서 했을 때 에러가 발생하면 쓰려고 남겨둔 것입니다. 추후에 필요없으면 삭제할 예정입니다!!
그리고 여기 보시면 한 줄 cors에 대해서 disable 하는 것을 추가했는데, 지금까지 문제가 되었던게 security가 cors에 대해서 풀어주는 부분이 없어서 corsfilter까지 가지 못해서 문제가 발생한 것이 아닌가 생각해서 추가해두었습니다.
근데 일단은 이렇게 수정해두었긴한데,,, swagger에 토큰 넣어서 테스트해보니까 제대로 동작하는 것 같더라구요?? 그래서 쩡킹 코드를 한 번 봐주시면 감사하겠습니다.
제가 생각한게 틀릴 확률도 높아서 이 pr은 아닌 것 같으면 그냥 코드 버리는게 나을 것 같긴합니다!! 지금 원래 상태로 유지
제가 최대한 꼼꼼하게 작성하려고 했는데 봐주시면 감사하겠습니다!
https://www.baeldung.com/spring-webflux-cors
해당 글을 참고해서 작성해보았습니다.
=> refactor : cors 설정 수정 

src/main/java/com/usememo/jugger/domain/calendar/dto/GetCalendarDto.java, src/main/java/com/usememo/jugger/domain/calendar/dto/PostCalendarDto.java, src/main/java/com/usememo/jugger/domain/calendar/entity/Calendar.java, src/main/java/com/usememo/jugger/domain/calendar/service/CalendarServiceImplementation.java
=> feat: 일정 추가 api 필드 추가

src/main/java/com/usememo/jugger/domain/calendar/repository/CalendarRepository.java, src/main/java/com/usememo/jugger/domain/category/repository/CategoryRepository.java, src/main/java/com/usememo/jugger/domain/chat/controller/ChatController.java, src/main/java/com/usememo/jugger/domain/chat/dto/DeleteResponse.java, src/main/java/com/usememo/jugger/domain/chat/repository/ChatRepository.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatService.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java, src/main/java/com/usememo/jugger/domain/link/repository/LinkRepository.java, src/main/java/com/usememo/jugger/domain/photo/repository/PhotoRepository.java, src/main/java/com/usememo/jugger/domain/user/controller/UserController.java, src/main/java/com/usememo/jugger/global/exception/ErrorCode.java, src/main/java/com/usememo/jugger/global/security/token/controller/AuthController.java
- #106 
전체 메모 삭제 기능을 추가하였습니다.
메모뿐만 아니라 카테고리, 사진, 링크, 일정 등 모든 것을 삭제시킵니다.
=> feat : 전체 메모 삭제

src/main/java/com/usememo/jugger/domain/photo/controller/PhotoController.java, src/main/java/com/usememo/jugger/domain/photo/dto/GetPhotoDto.java, src/main/java/com/usememo/jugger/domain/photo/repository/PhotoRepository.java, src/main/java/com/usememo/jugger/domain/photo/service/PhotoService.java, src/main/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementation.java, src/main/java/com/usememo/jugger/domain/user/controller/UserController.java, src/main/java/com/usememo/jugger/global/s3/controller/S3Controller.java, src/main/java/com/usememo/jugger/global/s3/service/S3ServiceImplementation.java, src/main/java/com/usememo/jugger/global/security/token/controller/AuthController.java, src/test/java/com/usememo/jugger/global/s3/service/S3ServiceImplementationTest.java
- #105 
기간으로 사진 조회하는 기능을 구현했습니다. 
하지만 이상하게 사진을 save할 때, createdAt이 저장되지 않는 것을 발견해서 우선적으로 updatedAt으로 기능이 동작하게 해두었습니다.
추후에 기능상의 문제가 생기면 수정이 필요해보입니다.
위의 문제 해결법을 아신다면 알려주세요 쩡킹
=> feat : 기간으로 사진 조회

.github/workflows/deploy.yml, src/main/java/com/usememo/jugger/domain/user/repository/UserRepository.java, src/main/java/com/usememo/jugger/global/exception/ErrorCode.java, src/main/java/com/usememo/jugger/global/security/token/controller/AuthController.java, src/main/java/com/usememo/jugger/global/security/token/domain/GoogleLoginRequest.java, src/main/java/com/usememo/jugger/global/security/token/domain/GoogleSignupRequest.java, src/main/java/com/usememo/jugger/global/security/token/service/GoogleOAuthService.java, src/main/java/com/usememo/jugger/global/security/token/service/GoogleOAuthService_v2.java
- #120
일단 카카오 로그인하고 구조를 똑같게 해서 구현했습니다.
v2 파일로 올린 형식으로 kakao 로그인도 수정할 예정입니다. 
PENDING이라는 상태를 줘서 추가 정보를 입력받아서 로그인이 구현되게끔 수정할 예정입니다.
우선 V1으로 배포하고 V2로 구조 전체 바꿔버릴게요!
=> feat : google  로그인 구현

src/main/java/com/usememo/jugger/domain/chat/dto/GetChatByCategoryDto.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java, src/main/java/com/usememo/jugger/global/security/token/service/GoogleOAuthService_v2.java
- #125 
채팅 관련해서 리턴값들을 수정하였습니다.
=> fix : 채팅 리턴 값 수정

src/main/java/com/usememo/jugger/domain/category/controller/CategoryController.java, src/main/java/com/usememo/jugger/domain/category/service/CategoryServiceImplementation.java, src/main/java/com/usememo/jugger/domain/chat/controller/ChatController.java, src/main/java/com/usememo/jugger/domain/chat/dto/GetChatByCategoryDto.java, src/main/java/com/usememo/jugger/domain/chat/entity/Chat.java, src/main/java/com/usememo/jugger/domain/chat/repository/ChatRepository.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatService.java, src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java, src/main/java/com/usememo/jugger/domain/photo/dto/PhotoDto.java, src/main/java/com/usememo/jugger/domain/photo/entity/Photo.java, src/main/java/com/usememo/jugger/global/s3/controller/S3Controller.java, src/main/java/com/usememo/jugger/global/s3/service/S3ServiceImplementation.java
- #127 
이제는 카테고리 없이 입력하면 temp 카테고리로 입력됩니다.
또한 이제 리턴값이 아래의 이미지처럼 type을 포함해서 전부 리턴합니다.
=> refactor : 채팅 리턴 값 수정

src/main/java/com/usememo/jugger/domain/calendar/controller/CalendarController.java, src/main/java/com/usememo/jugger/domain/calendar/dto/CalendarUpdateRequest.java, src/main/java/com/usememo/jugger/domain/calendar/dto/GetCalendarDto.java, src/main/java/com/usememo/jugger/domain/calendar/dto/UpdateRequest.java, src/main/java/com/usememo/jugger/domain/calendar/entity/Calendar.java, src/main/java/com/usememo/jugger/domain/calendar/repository/CalendarRepository.java, src/main/java/com/usememo/jugger/domain/calendar/service/CalendarService.java, src/main/java/com/usememo/jugger/domain/calendar/service/CalendarServiceImplementation.java, src/main/java/com/usememo/jugger/domain/photo/dto/PhotoResponse.java, src/main/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementation.java, src/main/java/com/usememo/jugger/global/exception/ErrorCode.java, src/main/java/com/usememo/jugger/global/response/BaseResponse.java
- #138
일정조회 및 수정 기능을 개발하였습니다.
- closes #138
=> feat : 일정조회 및 수정

src/main/java/com/usememo/jugger/domain/chat/service/ChatServiceImplementation.java, src/main/java/com/usememo/jugger/domain/link/dto/LinkListResponse.java, src/main/java/com/usememo/jugger/domain/link/service/LinkServiceImplementation.java, src/main/java/com/usememo/jugger/domain/photo/controller/PhotoController.java, src/main/java/com/usememo/jugger/domain/photo/dto/PhotoUpdateRequest.java, src/main/java/com/usememo/jugger/domain/photo/entity/Photo.java, src/main/java/com/usememo/jugger/domain/photo/repository/PhotoRepository.java, src/main/java/com/usememo/jugger/domain/photo/service/PhotoService.java, src/main/java/com/usememo/jugger/domain/photo/service/PhotoServiceImplementation.java, src/main/java/com/usememo/jugger/global/exception/ErrorCode.java
- #140 
사진 description 출력 및 수정
link depth 수정
=> refactor : 사진 description 수정 및 요구사항 반영
